import Head from "next/head";
import { Board } from "~/components/board";

import type { TCard } from "~/types/TCard";
import { Location } from "~/types/TCard";

import { Deck } from "~/components/deck";
import { Frame } from "~/components/frame";
import Graveyard from "~/components/graveyard";
import { Hand } from "~/components/hand";
import type { TBoard } from "~/types/TBoard";

export default function Home() {
  const playersHandCards: TCard[] = [
    {
      id: "1",
      location: Location.Hand,
      name: "BubbleCard1",
      opponentsHand: false,
    },
    {
      id: "2",
      location: Location.Hand,
      name: "BubbleCard2",
      opponentsHand: false,
    },
    {
      id: "3",
      location: Location.Hand,
      name: "BubbleCard3",
      opponentsHand: false,
    },
    {
      id: "4",
      location: Location.Hand,
      name: "BubbleCard4",
      opponentsHand: false,
    },
    {
      id: "5",
      location: Location.Hand,
      name: "BubbleCard5",
      opponentsHand: false,
    },
    {
      id: "6",
      location: Location.Hand,
      name: "BubbleCard6",
      opponentsHand: false,
    },
    {
      id: "7",
      location: Location.Hand,
      name: "BubbleCard7",
      opponentsHand: false,
    },
  ];
  const opponentsHandCards: TCard[] = [
    {
      id: "1",
      location: Location.Hand,
      name: "BubbleCard1",
      opponentsHand: false,
    },
    {
      id: "2",
      location: Location.Hand,
      name: "BubbleCard2",
      opponentsHand: false,
    },
    {
      id: "3",
      location: Location.Hand,
      name: "BubbleCard3",
      opponentsHand: false,
    },
    {
      id: "4",
      location: Location.Hand,
      name: "BubbleCard4",
      opponentsHand: false,
    },
    {
      id: "5",
      location: Location.Hand,
      name: "BubbleCard5",
      opponentsHand: false,
    },
    {
      id: "6",
      location: Location.Hand,
      name: "BubbleCard6",
      opponentsHand: false,
    },
    {
      id: "7",
      location: Location.Hand,
      name: "BubbleCard7",
      opponentsHand: false,
    },
  ];
  const opponentBoard: TBoard = {
    name: "opponent",
    opponentsBoard: true,
  };
  const playerBoard: TBoard = {
    name: "player",
    opponentsBoard: false,
  };
  return (
    <Frame>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-screen grid-cols-[1fr_10fr_1fr] grid-rows-4 flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Hand cards={opponentsHandCards}></Hand>
        <div className="col-span-3 grid grid-cols-subgrid">
          <Graveyard
            graveyard={{ name: "opponentsGraveyard", opponentsGraveyard: true }}
          ></Graveyard>
          <Board board={opponentBoard}></Board>
          <Deck deck={{ name: "opponent", opponentsDeck: true }}></Deck>
        </div>
        <div className="col-span-3 grid grid-cols-subgrid">
          <Deck deck={{ name: "player", opponentsDeck: false }}></Deck>
          <Board board={playerBoard}></Board>
          <Graveyard
            graveyard={{
              name: "opponentsGraveyard",
              opponentsGraveyard: false,
            }}
          ></Graveyard>
        </div>
        <Hand cards={playersHandCards}></Hand>
      </main>
    </Frame>
  );
}
