import {
  DndContext,
  type DragEndEvent,
  type DragStartEvent,
} from "@dnd-kit/core";
import Head from "next/head";
import { Card } from "~/components/card";
import Draggable from "~/components/draggable";
import Droppable, {
  isDroppableMonsterOpponent,
  isDroppableMonsterPlayer,
  type DroppableId,
} from "~/components/droppable";
import { Frame } from "~/components/frame";
import { useDraggingManager } from "~/hooks/dragging-manager";
import { useGameManager } from "~/hooks/game-manager";
import type { Card as TCard } from "~/server/types/models";
import { api } from "~/utils/api";
import { cn } from "~/utils/cn";

declare module "@dnd-kit/core" {
  export interface DragStartEvent {
    active: { id: string; data: { current: TCard } } | null;
  }

  export interface DragEndEvent {
    active: { id: string; data: { current: TCard } };
    over: { id: DroppableId } | null;
  }
}

export default function Game() {
  const {
    turn,
    turnCount,
    cardLocations,
    moveCard,
    winner,
    getCardLocation,
    getCardById,
  } = useGameManager();
  const { startDragging, stopDragging, moveItem, draggableId } =
    useDraggingManager();
  const isDraggingSpellFromHand =
    draggableId !== null &&
    getCardById(draggableId)?.type === "spell" &&
    getCardLocation(draggableId) === "player-hand";
  const isDraggingMonsterFromBoard =
    draggableId !== null &&
    getCardById(draggableId)?.type === "monster" &&
    getCardLocation(draggableId) === "player-board";
  const isDraggingMonsterFromHand =
    draggableId !== null &&
    getCardById(draggableId)?.type === "monster" &&
    getCardLocation(draggableId) === "player-hand";
  const hasSpellTarget =
    cardLocations["player-board"].length > 0 ||
    cardLocations["opponent-board"].length > 0;

  function handleDragStart(event: DragStartEvent) {
    const { active } = event;
    if (!active) return;

    // TODO: don't allow dragging cards if the conditions are not met. create a layer for that

    startDragging(active.id);
  }

  const { mutate: endTurn } = api.game.endTurn.useMutation();

  const canDragTo = (cardId: string, targetArea: DroppableId) => {
    const draggedCard = getCardById(cardId);
    if (!draggedCard) return false;

    const cardLocation = getCardLocation(cardId);
    console.log(
      "canDragTo",
      draggedCard,
      cardLocation,
      targetArea,
      isDroppableMonsterOpponent.test(targetArea),
      isDroppableMonsterPlayer.test(targetArea),
    );
    if (
      cardLocation === "player-hand" &&
      draggedCard.type === "monster" &&
      targetArea === "player-board"
    ) {
      // play monster from hand to board
      return true;
    } else if (
      cardLocation === "player-hand" &&
      draggedCard.type === "spell" &&
      (isDroppableMonsterOpponent.test(targetArea) ||
        isDroppableMonsterPlayer.test(targetArea))
    ) {
      // target spell to player's or opponent's monster
      return true;
    } else if (
      cardLocation === "player-board" &&
      draggedCard.type === "monster" &&
      isDroppableMonsterOpponent.test(targetArea)
    ) {
      // attack opponent's monster
      return true;
    }

    return false;
  };

  const handleDragEnd = (event: DragEndEvent) => {
    stopDragging();
    const { active, over } = event;
    if (!over) return;

    const draggedCard = getCardById(active.id);
    if (!draggedCard) return;

    if (canDragTo(active.id, over.id)) {
      moveItem(active.id, over.id);
    }
  };

  return (
    <Frame>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DndContext onDragStart={handleDragStart} onDragEnd={handleDragEnd}>
        <div className="relative h-full bg-[url('/background.jpg')] bg-cover bg-center">
          {/* turn info */}
          <div className="absolute left-4 top-1/2 -translate-y-1/2 text-center">
            <div className="text-3xl font-bold">Turn Count: {turnCount}</div>
            <div className="text-3xl font-bold">
              {turn === "player" ? "Your Turn" : "Opponent's Turn"}
            </div>
          </div>

          {/* game board anchor */}
          <div className="absolute left-1/2 top-1/2">
            {/* opponent */}
            <div className="absolute -top-[305px] left-[570px] -translate-x-1/2">
              <div className="h-card w-card bg-blue-300/50 text-white">
                {cardLocations["opponent-discard-pile"].map((card) => (
                  <div className="absolute" key={card.id}>
                    <Card card={card} hidden={false}></Card>
                  </div>
                ))}
              </div>
            </div>

            <div className="absolute -top-[305px] -translate-x-1/2">
              <div className="flex h-card w-[940px] gap-[10px] bg-blue-300/50">
                {cardLocations["opponent-board"].map((card) => (
                  <div key={card.id}>
                    <Droppable
                      id={`monster-opponent-${card.id}`}
                      enabled={
                        isDraggingSpellFromHand || isDraggingMonsterFromBoard
                      }
                    >
                      <Card card={card} hidden={false}></Card>
                    </Droppable>
                  </div>
                ))}
              </div>
            </div>

            <div className="absolute -left-[570px] -top-[305px] -translate-x-1/2">
              <div className="h-card w-card bg-green-400">
                {cardLocations["opponent-deck"].map((card) => (
                  <div className="absolute" key={card.id}>
                    <Card card={card} hidden></Card>
                  </div>
                ))}
              </div>
            </div>

            {/* player */}
            <div className="absolute -bottom-[305px] left-[570px] -translate-x-1/2">
              <div className="h-card w-card bg-green-400">
                {cardLocations["player-deck"].map((card) => (
                  <div
                    className={cn(
                      "absolute",
                      turn === "player" && "cursor-pointer",
                    )}
                    key={card.id}
                    onClick={() => {
                      if (turn !== "player") return;
                      console.log("draw card from player deck");
                      if (cardLocations["player-hand"].length < 5) {
                        moveCard({ cardId: card.id, to: "player-hand" });
                      }
                    }}
                  >
                    <Card card={card} hidden></Card>
                  </div>
                ))}
              </div>
            </div>

            <div className="absolute -bottom-[305px] -translate-x-1/2">
              <Droppable id="player-board" enabled={isDraggingMonsterFromHand}>
                <div className="flex h-card w-[940px] gap-[10px] bg-blue-300/50">
                  {cardLocations["player-board"].map((card) => (
                    <div key={card.id}>
                      <Droppable
                        id={`monster-player-${card.id}`}
                        enabled={isDraggingSpellFromHand}
                      >
                        <Draggable
                          id={card.id}
                          enabled={turn === "player"}
                          droppableIds={cardLocations["opponent-board"]
                            .filter(
                              (c) =>
                                card.type === "monster" &&
                                c.type === "monster" &&
                                c.currentSize < card.currentSize,
                            )
                            .map(
                              (c) => `monster-opponent-${c.id}` as DroppableId,
                            )}
                        >
                          <Card card={card} hidden={false}></Card>
                        </Draggable>
                      </Droppable>
                    </div>
                  ))}
                </div>
              </Droppable>
            </div>
            <div className="absolute -bottom-[305px] right-[570px] translate-x-1/2">
              <div className="h-card w-card bg-blue-300/50 text-white">
                {cardLocations["player-discard-pile"].map((card) => (
                  <div className="absolute" key={card.id}>
                    <Card card={card} hidden={false}></Card>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* hands */}
          <div className="absolute -top-48 left-1/2 -translate-x-1/2">
            <div className="pointer-events-none flex">
              {cardLocations["opponent-hand"].map((card) => (
                <div key={card.id} className="pointer-events-auto origin-top">
                  <Card card={card} hidden></Card>
                </div>
              ))}
            </div>
          </div>
          {turn === "player" && (
            <button
              className="absolute right-32 top-1/2 rounded-lg border bg-white p-4 text-center text-lg"
              onClick={() => endTurn()}
            >
              End Turn
            </button>
          )}
          <div className="absolute -bottom-10 left-1/2 -translate-x-1/2 scale-150 hover:bottom-20">
            <div className="pointer-events-none flex">
              {cardLocations["player-hand"].map((card) => (
                <div
                  key={card.id}
                  className="pointer-events-auto -mx-[45px] origin-bottom scale-50 transition-transform hover:z-10 hover:scale-100"
                >
                  <Draggable
                    id={card.id}
                    enabled={
                      turn === "player" &&
                      (getCardById(card.id)?.type === "monster" ||
                        (hasSpellTarget &&
                          getCardById(card.id)?.type === "spell"))
                    }
                    droppableIds={
                      cardLocations["player-board"].length < 5
                        ? ["player-board"]
                        : []
                    }
                  >
                    <Card card={card} hidden={false}></Card>
                  </Draggable>
                </div>
              ))}
            </div>
          </div>
        </div>
      </DndContext>
      {winner !== null && (
        <div className="">
          <div className="absolute inset-0 left-1/4 top-1/4 h-1/2 w-1/2 content-center justify-center bg-black/80 text-center text-6xl text-white">
            {winner === "player" && <p>You Won</p>}
            {winner === "opponent" && <p>You Lost</p>}
          </div>
        </div>
      )}
    </Frame>
  );
}
