on:
  push:
    branches:
      - main
      # TODO: remove
      - feat/*
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Rsync files to web server only after all checks passed
        run: |
          touch id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          cat id_rsa
          echo "key copied"

          rsync -avz --delete \
            --include="package.json" \
            --include="pnpm-lock.yaml" \
            --include="next.config.js" \
            --include=".next" \
            --include=".next/**" \
            --include="public" \
            --include="public/**" \
            --include="src" \
            --include="src/env.js" \
            --include="prisma" \
            --include="prisma/dev.db" \
            --include="node_modules" \
            --include="node_modules/**" \
            --exclude="*" \
            -e "ssh -o StrictHostKeyChecking=no -i id_rsa" . ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:/srv/${{ vars.APP_NAME }}

      # TODO: uncomment this block after resolving the issue with pm2 permissions
      # - name: Install dependencies on web server and deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ vars.SSH_HOST }}
      #     username: ${{ vars.SSH_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /srv/${{ vars.APP_NAME }}
      #       # pnpm install --frozen-lockfile
      #       pm2 restart ${{ vars.APP_NAME }}
