on:
  push:
    branches:
      - main
      # TODO: remove this line after finishing feature
      - feat/*
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: List contents of directories
        run: |
          ls -la .next
          ls -la public

      - name: Copy files to web server only after all checks passed
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            .next
            public
            package.json
            pnpm-lock.yaml
          target: "/srv/${{ vars.APP_NAME }}"

      - name: Install dependencies on web server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/${{ vars.APP_NAME }}
            pnpm install --frozen-lockfile
            pm2 restart ${{ vars.APP_NAME }}
